ci:
  skip: [ty]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
    -   id: clang-format
        exclude: \.(ts|tsx|js|jsx|json|mjs|cjs)$
        args: ["--style=file"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.10
  hooks:
    # Run the linter.
    - id: ruff
      args: [ "--unsafe-fixes", "--fix" ]
    # Run the formatter.
    - id: ruff-format

# typescript
- repo: https://github.com/biomejs/pre-commit
  rev: v2.1.2  # Use the latest released tag or your desired version
  hooks:
    - id: biome-check

# markdown
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.20.0
  hooks:
  - id: markdownlint-cli2
