[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["teleop_xr"]
artifacts = ["teleop_xr/cert.pem", "teleop_xr/key.pem"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "teleop_xr/_version.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "webxr/node_modules",
  "webxr/dist",
  "webxr/.vite",
]

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[project]
name = "teleop_xr"
dynamic = ["version"]
requires-python = ">=3.10"
description = "Turns your phone into a robot arm teleoperation device by leveraging the WebXR API"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
authors = [{ name = "Spes Robotics", email = "contact@spes.ai" }]
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "numpy",
  "transforms3d",
  "pytest",
  "requests",
  "websocket-client",
  "aiortc",
  "opencv-python",
  "av",
]

[project.urls]
Documentation = "https://github.com/SpesRobotics/teleop"
Source = "https://github.com/SpesRobotics/teleop"
Tracker = "https://github.com/SpesRobotics/teleop/issues"

[project.optional-dependencies]
utils = ["pin"]

[dependency-groups]
dev = [
  "pre-commit",
]
